### ISSUE TITLE
Error when loading BPF entities

### ISSUE THREAD

**Issue by nagyRS** [carfup/XTBPlugins.PCF2BPF#13] opened 2022-07-01 09:49 UTC
I'm getting an **"Object reference not set to an instance of an object"** error when loading the BPF entities with the tool. 
The connection with the Dataverse org is working fine, and the org has multiple BPF entities.
Thanks

**Comment by malkhawaja** [comment] 2022-07-04 19:43
I have the same issue!!

**Comment by carfup** [comment] 2022-07-05 07:08
Hello @nagyRS & @malkhawaja ,

Thanks for reporting the issue.
I'm not able to reproduce it, is there anything "special" with the BPFs in your organizations so I could figure out the issue ?

Example : BPFs with multiple entities, special fields, anything.

Another way to figure this out would be if possible for you to provide me a temporary access to your instance so I can debug it.

Let me know,

**Comment by MscrmTools** [comment] 2022-07-05 09:28
@nagyRS @malkhawaja, it seems the issue is more about loading PCF than BPF. Could you tell us if you installed or developed yourself some PCFs on the impacted environment?

**Comment by nagyRS** [comment] 2022-07-05 10:32
Hi @carfup  / @MscrmTools   - thanks for getting back to me.
I've uninstalled the tool and reinstalled it again and managed to make it work for a short while. When I started making changes  the tool crashed and when I reopened it, it produced the same error as above.
You're right there is status msg 'loading available PCF in your environment', but it's so quick I could not take a screenshot. I've tried it with multiple environments with the same result. We did not develop/install any PCFs only using oob components. Unfortunately I'm not able to give you access to orgs but managed to copy the error logs when the tool crashed - attached here. Thanks
[errorLog.txt](https://github.com/carfup/XTBPlugins.PCF2BPF/files/9045593/errorLog.txt)

**Comment by carfup** [comment] 2022-07-05 11:23
Thanks for your feedback @nagyRS.

Can you tell us is you are trying to apply a PCF to a field or edit an existing one ?
Which oob PCF is it ?

**Comment by nagyRS** [comment] 2022-07-05 12:03
@carfup - I was trying to modify an existing field on the BPF to change a Yes/No button to a toggle.

**Comment by malkhawaja** [comment] 2022-07-05 12:12
in my case I just press the button (Load BPF entities) then I am presented with this error:
![image](https://user-images.githubusercontent.com/43861985/177324503-2e6f5fcc-837b-44dd-bf4c-b8a343b9db7e.png)

and I tried it for another instance connection it loaded with no problems! but I am not sure what is wrong for my environment

**Comment by RA-Danny** [comment] 2022-07-14 09:55
Same as @malkhawaja for me. Just pressing the button "Load BPFs" leads to the object reference error...
I've tried with multiple orgs, always the same issue... :(

**Comment by carfup** [comment] 2022-07-14 13:08
Thanks all for your feedbacks.
May you try that version to solve the issue or get more details (if we are in that case please send me the details)
[Carfup.XTBPlugins.PCF2BPF.zip](https://github.com/carfup/XTBPlugins.PCF2BPF/files/9112019/Carfup.XTBPlugins.PCF2BPF.zip)
Waiting for your feedbacks.
Clément

**Comment by malkhawaja** [comment] 2022-07-14 13:18
@carfup how can we install this file?

**Comment by carfup** [comment] 2022-07-14 13:28
From XrmTooloBox go to : 
Configuration > Settings >Tab named "Path" > Click on "Open Xrm Toolbox Storage folder" > in the folder open the Plugins one > copy the DLL and replace the existing one from my previous message.

**Comment by nagyRS** [comment] 2022-07-18 11:45
Hi @carfup  - a different error this time.  Listing the steps I performed:
1. downloaded zip file from above
2. Extracted the zip
3. Found the path of old dll
4. replaced the old dll to the new one
5. restarted machine and xrm toolbox
6. opened xrm toolbox and connected to organisation
7. open pcf2bpf tool

The error now pops up before opening the tool. Details attached.

[UnhandledException.txt](https://github.com/carfup/XTBPlugins.PCF2BPF/files/9131560/UnhandledException.txt)
[ErrorDetails.txt](https://github.com/carfup/XTBPlugins.PCF2BPF/files/9131561/ErrorDetails.txt)
![UnhandledException](https://user-images.githubusercontent.com/23615494/179503890-3d040f4a-a609-4be5-a055-e5543aae0038.png)
![ErrorDetail](https://user-images.githubusercontent.com/23615494/179503902-92f60981-020d-40bd-999f-720c4cb3af5b.png)

Thank you

**Comment by carfup** [comment] 2022-07-18 11:49
@nagyRS 
My mistake here, a dll is missing when I build the project locally ...
Can you please try to add this one temporary to the Plugins folder : [Microsoft.ApplicationInsights.zip](https://github.com/carfup/XTBPlugins.PCF2BPF/files/9131605/Microsoft.ApplicationInsights.zip) ?
You may delete it once I figured out the issue here.

**Comment by nagyRS** [comment] 2022-07-18 13:22
@carfup  - this has worked. Thanks a lot ! 👍

**Comment by carfup** [comment] 2022-07-18 13:45
> @carfup - this has worked. Thanks a lot ! 👍

You mean it worked loading the plugin or it's fully fixed now ?

**Comment by nagyRS** [comment] 2022-07-18 14:00
> 

Both. I could load the plugin and I could change the control to a toggle

**Comment by carfup** [comment] 2022-07-18 14:09
@malkhawaja @RA-Danny can you please try this too to confirm the fix ?

**Comment by malkhawaja** [comment] 2022-07-18 17:47
Hi @carfup , I confirm that it is working perfectly now!

**Comment by carfup** [comment] 2022-07-18 18:03
I'll publish the update by tomorrow then.
Thanks for your feedbacks

**Comment by carfup** [comment] 2022-07-19 08:45
The version is now published on the XrmToolBox library.
Enjoy !

**Closed as completed by carfup** 2022-07-19 08:45 UTC
Labels: bug
